# Generated by Django 2.0 on 2019-04-04 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=25)),
                ('body', models.CharField(max_length=800)),
                ('date', models.DateField()),
                ('blogimg', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
